import './globals.css';

export const metadata = {
	title: 'StarterPack by Exosky',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='bg-gray-900'>
				{children}</body>
		</html>
	);
}
