'use client';

import { Header } from '../components/Header/Header';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='bg-gray-900'>
				<Header />
				{children}
			</body>
		</html>
	);
}
